#!/bin/sh

# Copyright (c) 2001-2007 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

usage() {
	echo "Usage: $0 backupsetname newhostname"
}

if ! [ "$1" ]; then
	usage
	exit 2
fi

# backup directory
bkd="/etc/backup/$1"

if ! [ -d "$bkd" ]; then
	echo "$bkd directory does not exist!"
	exit 3
fi
if ! [ -f "$bkd/dumplist" ]; then
	echo "$bkd/dumplist file does not exist, creating"
	touch $bkd/dumplist
fi
if [ -f "$bkd/conf" ]; then
	. $bkd/conf
fi

if [ -d "$datadir" ]; then
	cd $datadir
else
	echo "$datadir in $bkd/conf does not exist!"
	exit 5
fi

if ! [ "$2" ]; then
	usage
	exit 6
fi
cd $bkd
echo "Press <enter> when prompted for a passphrase.."
ssh-keygen -t rsa -b 4096 -f ${2}_sshkey
echo
echo "On the remote system, start uudecode in ~_backup/.ssh.."
echo "and cut-n-paste the following"
echo "no-pty,from=\"1.2.3.4\",no-port-forwarding,no-X11-forwarding,no-agent-forwarding $(cat ${2}_sshkey.pub)" | uuencode authorized_keys
mkdir $datadir/$2
chown _backup._backup $datadir/$2 ${2}_sshkey
echo "Example entry for $bkd/dumplist:"
echo "  sshdump://_backup@${2}/var"
