#!/bin/sh

# Copyright (c) 2008 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# where logs are
radlogdir=/var/log/radius
# where data is retained
retaindir=/var/backups/retain
# how may days old before we `retain' i.e. move elsewhere?
days=30

[ -f /etc/retain.conf ] && . /etc/retain.conf

if ! [ "$radacct" ]; then
	radacct="$radlogdir/radacct"
fi

if ! [ -d $radacct ]; then
	echo "radacct dir $radacct does not exist, aborting"
	exit 1
fi

if ! [ -d $retaindir ]; then
	echo "retention dir $retaindir does not exist, aborting"
	exit 1
fi

td=`mktemp -d /tmp/.retain.XXXXXXXXXX`

cd $radacct

# Make a list of files to archive; only do it once not only to
# conserve processing required, but also to make sure we back up
# what we later remove..
find * -type f -mtime -$days > $td/list

# Make sure to choose a unique filename, so we don't over-write data
fpattern="$retaindir/$(date +%Y/%m/%d-%H_%M_%S).$$.XXXXXXXXXXX"
outdir="$(dirname "$fpattern")"
mkdir -p "$outdir"
outfile="$(mktemp "$fpattern")"

if ! [ "$outfile" ]; then
	echo "Failed to create output file, aborting"
	exit 1
fi

tar cf - $(cat $td/list) | gzip -9 > $outfile
ls -l $outfile
tarlines=$(tar tvf $outfile | wc -l)
listlines=$(wc -l < $td/list)

if [ $tarlines -eq $listlines ]; then
	echo Successfully archived files, would
	echo "\# rm -- $(cat $td/list)"
fi
